export const videoList = [
  {
    id: 'kjhas-jkaskj-1',
    name: 'ACH',
    icon: '/img/ach-icon.png',
    video_banner: '/img/video-0.png',
    video_list: [
      {
        id: 'kjhas-jkaskj-video-1',
        name: 'Working Capital 101',
        video_banner: '/img/video-1.png',
        video_time: '03:10',
        video_link: 'a305sjr761',
      },
      {
        id: 'kjhas-jkaskj-video-2',
        name: 'Video Example Name',
        video_banner: '/img/video-2.png',
        video_time: '03:20',
        video_link: '8eq91j5xpi',
      },
      {
        id: 'kjhas-jkaskj-video-3',
        name: 'Video Example Name',
        video_banner: '/img/video-3.png',
        video_time: '03:40',
        video_link: '4efrqhpcbl',
      },
      {
        id: 'kjhas-jkaskj-video-4',
        name: 'Video Example Name',
        video_banner: '/img/video-4.png',
        video_time: '03:10',
        video_link: 'wyab8hag6g',
      },
      {
        id: 'kjhas-jkaskj-video-5',
        name: 'Video Example Name',
        video_banner: '/img/video-5.png',
        video_time: '03:05',
        video_link: 'wyab8hag6g',
      },
    ],
  },
  {
    id: 'kjhas-jkaskj-2',
    name: 'Business Cards',
    icon: '/img/ach-icon.png',
    video_banner: '/img/video-5.png',
    video_list: [
      {
        id: 'kjhas-jkaskj-video-7',
        name: 'Working Capital 101',
        video_banner: '/img/video-1.png',
        video_time: '03:10',
        video_link: 'a305sjr761',
      },
      {
        id: 'kjhas-jkaskj-video-8',
        name: 'Video Example Name',
        video_banner: '/img/video-2.png',
        video_time: '03:20',
        video_link: '8eq91j5xpi',
      },
      {
        id: 'kjhas-jkaskj-video-9',
        name: 'Video Example Name',
        video_banner: '/img/video-3.png',
        video_time: '03:40',
        video_link: '4efrqhpcbl',
      },
      {
        id: 'kjhas-jkaskj-video-10',
        name: 'Video Example Name',
        video_banner: '/img/video-4.png',
        video_time: '03:10',
        video_link: 'wyab8hag6g',
      },
      {
        id: 'kjhas-jkaskj-video-11',
        name: 'Video Example Name',
        video_banner: '/img/video-5.png',
        video_time: '03:05',
        video_link: 'wyab8hag6g',
      },
    ],
  },
  {
    id: 'kjhas-jkaskj-3',
    name: 'Merchant Services',
    icon: '/img/ach-icon.png',
    video_banner: '/img/video-1.png',
    video_list: [
      {
        id: 'kjhas-jkaskj-video-12',
        name: 'Working Capital 101',
        video_banner: '/img/video-1.png',
        video_time: '03:10',
        video_link: 'a305sjr761',
      },
      {
        id: 'kjhas-jkaskj-video-13',
        name: 'Video Example Name',
        video_banner: '/img/video-2.png',
        video_time: '03:20',
        video_link: '8eq91j5xpi',
      },
      {
        id: 'kjhas-jkaskj-video-14',
        name: 'Video Example Name',
        video_banner: '/img/video-3.png',
        video_time: '03:40',
        video_link: '4efrqhpcbl',
      },
      {
        id: 'kjhas-jkaskj-video-15',
        name: 'Video Example Name',
        video_banner: '/img/video-4.png',
        video_time: '03:10',
        video_link: 'wyab8hag6g',
      },
    ],
  },
  {
    id: 'kjhas-jkaskj-1',
    name: 'Working Capital',
    icon: '/img/ach-icon.png',
    video_banner: '/img/video-2.png',
    video_list: [
      {
        id: 'kjhas-jkaskj-video-1',
        name: 'Working Capital 101',
        video_banner: '/img/video-1.png',
        video_time: '03:10',
        video_link: 'a305sjr761',
      },
      {
        id: 'kjhas-jkaskj-video-2',
        name: 'Video Example Name',
        video_banner: '/img/video-2.png',
        video_time: '03:20',
        video_link: '8eq91j5xpi',
      },
      {
        id: 'kjhas-jkaskj-video-3',
        name: 'Video Example Name',
        video_banner: '/img/video-3.png',
        video_time: '03:40',
        video_link: '4efrqhpcbl',
      },
      {
        id: 'kjhas-jkaskj-video-4',
        name: 'Video Example Name',
        video_banner: '/img/video-4.png',
        video_time: '03:10',
        video_link: 'wyab8hag6g',
      },
      {
        id: 'kjhas-jkaskj-video-5',
        name: 'Video Example Name',
        video_banner: '/img/video-5.png',
        video_time: '03:05',
        video_link: 'wyab8hag6g',
      },
    ],
  },
  {
    id: 'kjhas-jkaskj-1',
    name: 'ACH',
    icon: '/img/ach-icon.png',
    video_banner: '/img/video-3.png',
    video_list: [
      {
        id: 'kjhas-jkaskj-video-1',
        name: 'Working Capital 101',
        video_banner: '/img/video-1.png',
        video_time: '03:10',
        video_link: 'a305sjr761',
      },
      {
        id: 'kjhas-jkaskj-video-2',
        name: 'Video Example Name',
        video_banner: '/img/video-2.png',
        video_time: '03:20',
        video_link: '8eq91j5xpi',
      },
      {
        id: 'kjhas-jkaskj-video-3',
        name: 'Video Example Name',
        video_banner: '/img/video-3.png',
        video_time: '03:40',
        video_link: '4efrqhpcbl',
      },
      {
        id: 'kjhas-jkaskj-video-4',
        name: 'Video Example Name',
        video_banner: '/img/video-4.png',
        video_time: '03:10',
        video_link: 'wyab8hag6g',
      },
      {
        id: 'kjhas-jkaskj-video-5',
        name: 'Video Example Name',
        video_banner: '/img/video-5.png',
        video_time: '03:05',
        video_link: 'wyab8hag6g',
      },
    ],
  },
  {
    id: 'kjhas-jkaskj-1',
    name: 'ACH',
    icon: '/img/ach-icon.png',
    video_banner: '/img/video-4.png',
    video_list: [
      {
        id: 'kjhas-jkaskj-video-1',
        name: 'Working Capital 101',
        video_banner: '/img/video-1.png',
        video_time: '03:10',
        video_link: 'a305sjr761',
      },
      {
        id: 'kjhas-jkaskj-video-2',
        name: 'Video Example Name',
        video_banner: '/img/video-2.png',
        video_time: '03:20',
        video_link: '8eq91j5xpi',
      },
      {
        id: 'kjhas-jkaskj-video-3',
        name: 'Video Example Name',
        video_banner: '/img/video-3.png',
        video_time: '03:40',
        video_link: '4efrqhpcbl',
      },
    ],
  },
];
