export const dataGetGuest = {
  data: {
    users: [
      {
        id: 'guest_1',
        first_name: 'Guest',
        last_name: '1',
        email: 'guestOne@gmail.com',
        title: 'Indentifee Company',
        status: 'active',
      },
    ],
  },
};

export const dataGetThreeGuest = {
  data: {
    users: [
      {
        id: 'guest_1',
        first_name: 'Guest',
        last_name: '1',
        email: 'guestOne@gmail.com',
        title: 'Indentifee Company',
        status: 'active',
      },
      {
        id: 'guest_2',
        first_name: 'Guest2',
        last_name: '2',
        email: 'guestTwo@gmail.com',
        title: 'Indentifee Company',
        status: 'active',
      },
      {
        id: 'guest_3',
        first_name: 'Guest3',
        last_name: '3',
        email: 'guestThree@gmail.com',
        title: 'Indentifee Company',
        status: 'active',
      },
    ],
  },
};

export const getUsers = {
  data: {
    users: [
      {
        id: 'user_id_1',
        first_name: 'First Name 1',
        last_name: 'Last Name 1',
        email: 'emailUser1@helloBuild.co',
        location: 'location 1',
        title: 'title 1',
        description: 'description 1',
        tags: null,
        avatar: null,
        status: 'active',
        role: 'role_1',
        last_access: '2021-11-29T15:37:00.558Z',
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_1',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 1Test',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: false,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_2',
        first_name: 'First Name 2',
        last_name: 'Last Name 2',
        email: 'emailUser2@helloBuild.co',
        location: 'location 2',
        title: 'title 2',
        description: 'description 2',
        tags: null,
        avatar: null,
        status: 'deactivated',
        role: 'role_2',
        last_access: null,
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_2',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 2',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_3',
        first_name: 'First Name 3',
        last_name: 'Last Name 3',
        email: 'emailUser3@helloBuild.co',
        location: 'location 3',
        title: 'title 3',
        description: 'description 3',
        tags: null,
        avatar: null,
        status: 'invited',
        role: 'role_3',
        last_access: null,
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_3',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 3',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_4',
        first_name: 'First Name 4',
        last_name: 'Last Name 4',
        email: 'emailUser4@helloBuild.co',
        location: 'location 4',
        title: 'title 4',
        description: 'description 4',
        tags: null,
        avatar: null,
        status: 'invited',
        role: 'role_4',
        last_access: null,
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_4',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 4',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_5',
        first_name: 'First Name 5',
        last_name: 'Last Name 5',
        email: 'emailUser5@helloBuild.co',
        location: 'location 5',
        title: 'title 5',
        description: 'description 5',
        tags: null,
        avatar: null,
        status: 'invited',
        role: 'role_5',
        last_access: null,
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_5',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 5',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_6',
        first_name: 'First Name 6',
        last_name: 'Last Name 6',
        email: 'emailUser6@helloBuild.co',
        location: 'location 6',
        title: 'title 6',
        description: 'description 6',
        tags: null,
        avatar: null,
        status: 'invited',
        role: 'role_6',
        last_access: null,
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_6',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 6',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_7',
        first_name: 'First Name 7',
        last_name: 'Last Name 7',
        email: 'emailUser7@helloBuild.co',
        location: 'location 7',
        title: 'title 7',
        description: 'description 7',
        tags: null,
        avatar: null,
        status: 'invited',
        role: 'role_7',
        last_access: null,
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_7',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 7',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_8',
        first_name: 'First Name 8',
        last_name: 'Last Name 8',
        email: 'emailUser8@helloBuild.co',
        location: 'location 8',
        title: 'title 8',
        description: 'description 8',
        tags: null,
        avatar: null,
        status: 'invited',
        role: 'role_8',
        last_access: null,
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_8',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 8',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_9',
        first_name: 'First Name 9',
        last_name: 'Last Name 9',
        email: 'emailUser9@helloBuild.co',
        location: 'location 9',
        title: 'title 9',
        description: 'description 9',
        tags: null,
        avatar: null,
        status: 'active',
        role: 'role_9',
        last_access: '2029-09-09T20:02:29.430Z',
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_9',
          name: 'Rol Marisol',
          icon: 'supervised_user_circle',
          description: 'description 9',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: false,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
      {
        id: 'user_id_10',
        first_name: 'First Name 10',
        last_name: 'Last Name 10',
        email: 'emailUser10@helloBuild.co',
        location: 'location 10',
        title: 'title 10',
        description: 'description 10',
        tags: null,
        avatar: null,
        status: 'active',
        role: 'role_10',
        last_access: '2021-08-13T04:57:49.322Z',
        last_page: null,
        phone: null,
        tenant_id: '000000000000',
        roleInfo: {
          id: 'role_id_10',
          name: 'Admin',
          icon: 'supervised_user_circle',
          description: 'description 10',
          ip_access: null,
          enforce_tfa: false,
          module_list: null,
          collection_list: null,
          admin_access: true,
          app_access: true,
          tenant_id: '000000000000',
        },
      },
    ],
    pagination: {
      limit: 10,
      page: 1,
      totalPages: 4,
      count: 33,
    },
  },
};
